version: '3'
services:
  dbpostgres:
    image: postgres
    volumes:
      - ./data:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: movieapp